name: JS Test Workflow

on:[push]

job:
	check-code:
		runs-on: ubuntu-latest #nutzt virtuellen Linux-Server von Github
	steps:
		-name: Code auschecken
		-uses: actions/checkout@v4 #kopiert meinen Code auf Server

		-name: Node.js installieren
		-uses: actions/setup-node@v4
		-with:
			node-version: '20'

		-name: Test ausführen
		-run: npm test #führt Befehl aus package.json aus